[package]
name = "sonictunes"
version = "0.1.0"
edition = "2024"

[dependencies]
libmpv2 = "5.0.1"
rand = "0.9.2"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = "1.0.228"
serde_json = "1.0.145"
